---
- hosts: web-server
  become: true
  tasks:
   - name: Replacing web container
     script: /opt/playbooks/recreate-web-container.sh 8090
   - name: Restarting docker service
     shell: systemctl restart docker
     ignore_errors: yes
   - name: Creating docker container
     shell: docker run -d --name tomcat-demo -p 8090:8080 kesh1990/tomcat-demo
