---
- hosts: web-server
  become: true
  tasks:
   - name: Stop previous version docker
     shell: docker stop tomcat-demo
     ignore_errors: yes
   - name: Remove stopped container
     shell: docker rm -vf tomcat-demo    
     ignore_errors: yes
   - name: Remove docker images
     shell: docker image rm -f kesh1990/tomcat-demo
     ignore_errors: yes
   - name: Restarting docker service
     shell: systemctl restart docker
     ignore_errors: yes
   - name: Creating docker container
     shell: docker run -d --name tomcat-demo -p 8090:8080 kesh1990/tomcat-demo
